// 首页壁纸
export const Wallpaper = [
  "https://cdn.luoyuanxiang.top/img/bg/1.webp",
  "https://cdn.luoyuanxiang.top/img/bg/2.webp",
  "https://cdn.luoyuanxiang.top/img/bg/3.webp",
  "https://cdn.luoyuanxiang.top/img/bg/4.webp",
  "https://cdn.luoyuanxiang.top/img/bg/5.webp",
  "https://cdn.luoyuanxiang.top/img/bg/6.webp",
  "https://cdn.luoyuanxiang.top/img/bg/7.webp",
  "https://cdn.luoyuanxiang.top/img/bg/8.webp",
  "https://cdn.luoyuanxiang.top/img/bg/9.webp",
  "https://cdn.luoyuanxiang.top/img/bg/10.webp",
  "https://cdn.luoyuanxiang.top/img/bg/11.webp",
  "https://cdn.luoyuanxiang.top/img/bg/12.webp",
  "https://cdn.luoyuanxiang.top/img/bg/13.webp",
  "https://cdn.luoyuanxiang.top/img/bg/14.webp",
  "https://cdn.luoyuanxiang.top/img/bg/15.webp",
  "https://cdn.luoyuanxiang.top/img/bg/16.webp",
  "https://cdn.luoyuanxiang.top/img/bg/17.webp",
  "https://cdn.luoyuanxiang.top/img/bg/18.webp",
  "https://cdn.luoyuanxiang.top/img/bg/19.webp",
];
