name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v4

      - name: 安装 Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装 pnpm
        run: |
          export TZ='Asia/Shanghai'
          npm install pnpm -g --registry=https://registry.npmmirror.com

      - name: 缓存 node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: 缓存构建产物
        uses: actions/cache@v4
        id: cache-dist
        with:
          path: docs/.vitepress/dist
          key: ${{ runner.OS }}-dist-${{ hashFiles('**/pnpm-lock.yaml', '**.md', 'docs/.vitepress/**') }}

      - name: 安装依赖
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          pnpm install --registry=https://registry.npmmirror.com

      - name: 生成静态文件
        if: steps.cache-dist.outputs.cache-hit != 'true'
        run: |
          pnpm run docs:build

      - name: 部署
        working-directory: ./docs/.vitepress/dist
        run: |
          git init
          git checkout -b main
          git add -A
          git -c user.name='luoyuanxiang' -c user.email='1141306760@qq.com' commit -m 'Updated By Github Actions'
          git remote add origin https://${{ secrets.BLOG_TOKEN }}@github.com/luoyuanxiang/luoyuanxiang.github.io.git
          git push origin main -f -q